FROM node:18

WORKDIR /app

COPY client/package*.json ./client/

RUN cd /app/client && npm install --legacy-peer-deps

COPY client/src ./client/src
COPY client/jest.config.cjs ./client/
COPY client/jest.setup.cjs ./client/
COPY client/.babelrc ./client/
COPY client/.env.test ./client/

WORKDIR /app/client

CMD ["npm", "test", "--", "--coverage", "--passWithNoTests"]
